// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlF-Y_zzISXvaEXL-gyW38di7uZ5zV1XA',
    appId: '1:784136586253:android:715178f534239895228144',
    messagingSenderId: '784136586253',
    projectId: 'hrmapp-1573814872457',
    databaseURL: 'https://hrmapp-1573814872457.firebaseio.com',
    storageBucket: 'hrmapp-1573814872457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWiz7eRGcDAKnAaTnDkk7N9zgc9iwYFVY',
    appId: '1:784136586253:ios:39cf03af193b47c4228144',
    messagingSenderId: '784136586253',
    projectId: 'hrmapp-1573814872457',
    databaseURL: 'https://hrmapp-1573814872457.firebaseio.com',
    storageBucket: 'hrmapp-1573814872457.firebasestorage.app',
    androidClientId: '784136586253-3pa6lo7ti0icbkmhgj45pt1k3d9paaln.apps.googleusercontent.com',
    iosClientId: '784136586253-54aq4doi77pdqvub229qac8ohqjqdnos.apps.googleusercontent.com',
    iosBundleId: 'in.u30days.ezhrm',
  );
}
