// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiKDh-ZhR1UQZZ2dAJ8fRUn9QVU1QbqWk',
    appId: '1:824893103076:web:d7fc7e1dfc5e962d7345f1',
    messagingSenderId: '824893103076',
    projectId: 'ezhrm-cefe3',
    authDomain: 'ezhrm-cefe3.firebaseapp.com',
    storageBucket: 'ezhrm-cefe3.firebasestorage.app',
    measurementId: 'G-WKM0SV3W4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBki0EwsQIz5P4QFkZWHmEp4d8-ef6jYnM',
    appId: '1:824893103076:android:11df8d53c026211b7345f1',
    messagingSenderId: '824893103076',
    projectId: 'ezhrm-cefe3',
    storageBucket: 'ezhrm-cefe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp4Qpwk0L2-PY0HHxe2Ar_l6mpFOZM-IE',
    appId: '1:824893103076:ios:d6e4c01d0edc76c57345f1',
    messagingSenderId: '824893103076',
    projectId: 'ezhrm-cefe3',
    storageBucket: 'ezhrm-cefe3.firebasestorage.app',
    iosBundleId: 'com.example.ezhrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp4Qpwk0L2-PY0HHxe2Ar_l6mpFOZM-IE',
    appId: '1:824893103076:ios:d6e4c01d0edc76c57345f1',
    messagingSenderId: '824893103076',
    projectId: 'ezhrm-cefe3',
    storageBucket: 'ezhrm-cefe3.firebasestorage.app',
    iosBundleId: 'com.example.ezhrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiKDh-ZhR1UQZZ2dAJ8fRUn9QVU1QbqWk',
    appId: '1:824893103076:web:9c494bad4eb06c5d7345f1',
    messagingSenderId: '824893103076',
    projectId: 'ezhrm-cefe3',
    authDomain: 'ezhrm-cefe3.firebaseapp.com',
    storageBucket: 'ezhrm-cefe3.firebasestorage.app',
    measurementId: 'G-GFR0ZDWJC8',
  );
}
